version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi.deploy:application
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:  
      - ./data:/var/lib/postgres/data
   