version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres
    container_namer: db
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgres/data